export const GET_DASHBOARD_DETAILS_SUCCESS = "GET_DASHBOARD_DETAILS_SUCCESS";
export const GET_DASHBOARD_DETAILS_FAIL = "GET_DASHBOARD_DETAILS_FAIL";
export const SET_LOADER_DASHBOARD = "SET_LOADER_DASHBOARD";
export const NEW_USER_DASHBOARD = "NEW_USER_DASHBOARD";
