export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_FAIL = "GET_TRANSACTIONS_FAIL";
export const SET_TRANSACTION_LOADER = "SET_TRANSACTION_LOADER";
export const SET_TRANSACTION_INDIVIDUAL_SUCCESS =
  "SET_TRANSACTION_INDIVIDUAL_SUCCESS";
export const SET_TRANSACTION_INDIVIDUAL_FAIL =
  "SET_TRANSACTION_INDIVIDUAL_FAIL";
